apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keyserver.fullname" . }}
  labels:
    {{- include "keyserver.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "keyserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "keyserver.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [
            "-max-size", {{ .Values.max_key_size | quote }},
            "-srv-port", {{ .Values.service.port | quote }},
          ]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /key/0
              port: http
          readinessProbe:
            httpGet:
              path: /key/0
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
